name: "GKE Terraform"

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  terraform:
    env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SECRET }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gke_tf
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve
  

